### ISSUE TITLE
VS2017 Debug x64 build of Starter Project gives "C1128: number of sections exceeded object file format limit: compile with /bigobj

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp.StarterProject#16]
```
1>C:\Code\ApprovalTests.cpp.StarterProject\tests\main.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```

**Comment by claremacrae** [comment]
This happened with:

* v.10.4.0 release: https://github.com/approvals/ApprovalTests.cpp.StarterProject/runs/1276693247?check_suite_focus=true
* v.10.5.0 release: https://github.com/approvals/ApprovalTests.cpp.StarterProject/runs/1350196448?check_suite_focus=true

I can reproduce it in a VM on my Mac too

**Comment by claremacrae** [comment]
I can confirm that the 10.3.0 build still works in VS2017 and the 10.4.0 does not.

Significant additions in 10.4.0 are:

* CppUTest support - but all code is #ifdef'd out
* EnvironmentVariableReporter
* ReporterFactory

**Comment by claremacrae** [comment]
With the v.10.4.0 version of the starter project checked out, removing both these suppressed the problem:

* EnvironmentVariableReporter
* ReporterFactory

If ReporterFactory is added back, the problem occurs.

**Comment by claremacrae** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=msvc-160

**Comment by claremacrae** [comment]
It's only the Debug x64 build that fails - and only in VS2017.

Debug x86 and both Release builds work fine in VS2017.

And all 4 work fine in VS2019.

**Comment by claremacrae** [comment]
This is now fixed, by adding the `/bigobj` C++ compiler argument to the one failing configuration
